train_stages: 1
cur_stage: 1
switch_error: 0.22
optim: adam
optim_conf:
  lr: 1e-3
  betas: [ 0.9, 0.999 ]
  eps: 1e-8
  weight_decay: 0.0
  amsgrad: False
sch: step
sch_step:
  gamma: 0.1
  stage: 4
loss:
#  pde_loss: NSLoss
  observe_rmsd_loss_weight: 1.0
  observe_dis_loss_weight: 0.01
#  pde_loss_weight: 1.0
main_conf:
  run_mode: train
train_conf:
  batch_size: 512
  epoch: 30
  eval_freq: 100
  log_freq: 0.0001
  print_frequency: 50

