norm:
  time_norm: False
  max_t: 30
observe_data:
  sampler: UniformSampler
  sampler_conf:
    batch_size: 1
    replace: False
  reweighting: NoReWeighting
  reweighting_conf: None
  n_eval_sections: 0
  val_ratio: 0.1
  limit: -1
  max_len: 256
