norm:
  time_norm: False
  max_t: 30
observe_data:
  sampler: UniformSampler
  sampler_conf:
    batch_size: 128
    replace: False
  reweighting: NoReWeighting
  reweighting_conf: None
  n_eval_sections: 0
  train_size: 0.8
  limit: -1
  max_len: 256
